### ISSUE TITLE
Rename Python scripts to be more indicative of purpose

### ISSUE THREAD

**Issue by bannanc** [MobleyLab/off-ffcompare#17]
Ok, similar to issue #9 This file name does not describe what the script does. I would expect this script to compare the FF's, but this does minimization for some of the force fields. I'm not sure what the best new name would be. 
FFminimizations.py? or 4FFminimizations?

**Comment by vtlim** [comment]
Good point, @bannanc . What about `minimizeOEMol.py` or something similar, since they all have to go through an OEMol first? Presumably, it should also work for a set of SDF files and maybe can be extended to other minimizations.
@dkyu, feel free to weigh in! 

Tangentially, should we leave the OPLS minimization script separate, since it doesn't require the openeye tools?

**Comment by bannanc** [comment]
I don't see any reason to combine the python scripts. Its not like we're developing a tool that I expect a lot of people to want to use. I think in the long run the more interesting information from this project will be the data not the scripts.

**Comment by vtlim** [comment]
Suggested renaming of files. Comments and suggestions welcome! @bannanc, @dkyu, @nthi0625 
* OPLS.py --> minimizeOPLS.py
  * Since minimization with OPLS force fields
* RMSD.py --> calcGeomRMSD.py
  * Since RMSD can also refer to relative energies, etc. 
* ffcompare.py --> minimizeSet.py (I'm iffy on this)
  * Since we have a set of force fields to use...

**Comment by vtlim** [comment]
Final thoughts:
* ffcompare.py --> min_oe_openMM.py
* OPLS.py --> min_opls.py

**Comment by vtlim** [comment]
Fix in #33
