### ISSUE TITLE
Update smi2sdf.py

### ISSUE THREAD

**Issue by vtlim** [MobleyLab/off-ffcompare#29]
* add command line inputs
* use mol2 file format?

**Comment by bannanc** [comment]
@vtlim The point of this script is to be able to use smiles strings to get us to the same point as the filter database sdf files. 

I see two options
1. Make sdf file that can be fed into the GenMol2.py script 

 
2. Use a SMILES file with the format: 
```
SMILES       Molecule Name
```
and update GenMol2.py to be able to generate mol2 files from SMILES or SDF files. 

I'm partial to 1. since we we're not likely to want to do this from a large list of smiles strings, but I'll leave it up to you.

**Comment by vtlim** [comment]
Addressed by #33.
