### ISSUE TITLE
Does OPLS.py work based on command line inputs?

### ISSUE THREAD

**Issue by vtlim** [MobleyLab/off-ffcompare#34]
The command line argument for OPLS.py calls for "Path to directory containing all mol2 files to be minimized." and passes this into the OPLSmin function. However, the OPLSmin function specifies that it takes one mol2 file for minimization. Which is it?

Also, the variable `cmd` uses "input_location" and "output_location". Is this where they're hardwired to go to in your directory, or are these supposed to be renamed, to something like "OPLS2005" for example?

**Comment by vtlim** [comment]
Also remove extra spaces in front of lines 51, 52, 59, 60

**Comment by nthi0625** [comment]
@vtlim :Since I am using the slurm file to run OPLS.py, my for loop is in the slurm file in which OPLS.py will be running.
the "input_location" and "output_location" will be the directory that contain the input and output mol2 file since 'opttype' variable already specified the name of each force-field in the 'if' statement, I am not sure if that is your question.

**Comment by vtlim** [comment]
addressed with #42
